POST https://api.telegram.org/bot5229024653:AAF7a7Zc6ouaqMIlUwDh2AYPLdEFoMZEENI/sendMessage
content-type: application/json

{
    "chat_id": -381122412,
    "text" : "Morning people!~ \n\nFirst things first to start your day 👇",
    "parse_mode" : "markdown",
    "reply_markup" : {
        "inline_keyboard" : [
            [
                {
                    "text" : "Send service feedback 💌",
                    "url" : "http://telegram.me/ilc_sf_bot?start=start"
                }
            ]
        ]
   }
}

###

POST https://api.telegram.org/bot5229024653:AAF7a7Zc6ouaqMIlUwDh2AYPLdEFoMZEENI/sendMessage
content-type: application/json

{
    "chat_id": -381122412,
    "text" : "⏰ Start writing down your thoughts soon.",
    "parse_mode" : "markdown",
    "reply_markup" : {
        "inline_keyboard" : [
            [
                {
                    "text" : "Send service feedback 💌",
                    "url" : "http://telegram.me/ilc_sf_bot?start=start"
                }
            ]
        ]
   }
}

###

POST https://api.telegram.org/bot5229024653:AAF7a7Zc6ouaqMIlUwDh2AYPLdEFoMZEENI/sendMessage
content-type: application/json

{
    "chat_id": -381122412,
    "text" : "⏳ Few more minutes to go! If you haven't started on your service feedback, start typing!",
    "parse_mode" : "markdown",
    "reply_markup" : {
        "inline_keyboard" : [
            [
                {
                    "text" : "Send service feedback 💌",
                    "url" : "http://telegram.me/ilc_sf_bot?start=start"
                }
            ]
        ]
   }
}

###
