
POST https://api.telegram.org/bot5229024653:AAF7a7Zc6ouaqMIlUwDh2AYPLdEFoMZEENI/sendMessage
content-type: application/json

{
    "chat_id" : -777532938,
    "text" : "test message"
}

### send file to BFC group chat
curl -F document=@"Downloads/ServiceFeedback-BoldestforChrist2–12Feb2022.pdf" https://api.telegram.org/bot5229024653:AAF7a7Zc6ouaqMIlUwDh2AYPLdEFoMZEENI/sendDocument?chat_id=-381122412